//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("System.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Resource.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Small = -19474,
        }
    }
}
